huh_encore:
    js_entries:
        - { name: contao-bootstrap-hover-dropdown-bundle, file: 'vendor/heimrichhannot/contao-bootstrap-hover-dropdown-bundle/src/Resources/public/js/contao-bootstrap-hover-dropdown-bundle.es6.js' }
    unset_global_keys:
        js:
            - bootstrap-hover-dropdown