services:
  _defaults:
    autowire: true

  HeimrichHannot\BootstrapHoverDropdownBundle\:
    resource: '../../{Asset}/*'
    autoconfigure: true

  HeimrichHannot\BootstrapHoverDropdownBundle\EventListener\GeneratePageListener:
    public: true